### ISSUE TITLE
日本語翻訳 Tracking Issue

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/plugin-handbook#16]
このissueは、プラグイン開発者ハンドブックの日本語化にあたり、原文の対象ページをリストアップし、各ページの進捗を管理するものです。

- [x] [Index](https://developer.wordpress.org/plugins) #14
- [x] [Introduction to Plugin Development](https://developer.wordpress.org/plugins/intro) #4
- [x] [Introduction to Plugin Development > What is a Plugin?](https://developer.wordpress.org/plugins/intro/what-is-a-plugin) #6
- [x] [Plugin Basics](https://developer.wordpress.org/plugins/plugin-basics) #21
- [ ] [Plugin Basics > Header Requirements](https://developer.wordpress.org/plugins/plugin-basics/header-requirements)
- [ ] [Plugin Basics > Including a Software License](https://developer.wordpress.org/plugins/plugin-basics/including-a-software-license)
- [ ] [Plugin Basics > Activation / Deactivation Hooks](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks)
- [ ] [Plugin Basics > Uninstall Methods](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods)
- [ ] [Plugin Basics > Best Practices](https://developer.wordpress.org/plugins/plugin-basics/best-practices)
- [ ] [Plugin Basics > Determining Plugin and Content Directories](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories)
- [x] [Plugin Security](https://developer.wordpress.org/plugins/security) #30
- [ ] [Plugin Security > Checking User Capabilities](https://developer.wordpress.org/plugins/security/checking-user-capabilities)
- [ ] [Plugin Security > Data Validation](https://developer.wordpress.org/plugins/security/data-validation)
- [ ] [Plugin Security > Securing (sanitizing) Input](https://developer.wordpress.org/plugins/security/securing-input)
- [ ] [Plugin Security > Securing (escaping) Output](https://developer.wordpress.org/plugins/security/securing-output)
- [ ] [Plugin Security > Nonces](https://developer.wordpress.org/plugins/security/nonces)
- [ ] [Hooks](https://developer.wordpress.org/plugins/hooks)
- [ ] [Hooks > Actions](https://developer.wordpress.org/plugins/hooks/actions)
- [ ] [Hooks > Filters](https://developer.wordpress.org/plugins/hooks/filters)
- [ ] [Hooks > Custom Hooks](https://developer.wordpress.org/plugins/hooks/custom-hooks)
- [ ] [Hooks > Advanced Topics](https://developer.wordpress.org/plugins/hooks/advanced-topics)
- [ ] [Privacy](https://developer.wordpress.org/plugins/privacy)
- [ ] [Privacy > Policy Content](https://developer.wordpress.org/plugins/privacy/suggesting-text-for-the-site-privacy-policy)
- [ ] [Privacy > Personal Data Export](https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-exporter-to-your-plugin)
- [ ] [Privacy > Personal Data Erasure](https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-eraser-to-your-plugin)
- [ ] [Privacy > Advanced Topics](https://developer.wordpress.org/plugins/privacy/privacy-related-options-hooks-and-capabilities)
- [x] [Administration Menus](https://developer.wordpress.org/plugins/administration-menus) #24
- [ ] [Administration Menus > Top-Level Menus](https://developer.wordpress.org/plugins/administration-menus/top-level-menus)
- [ ] [Administration Menus > Sub-Menus](https://developer.wordpress.org/plugins/administration-menus/sub-menus)
- [ ] [Shortcodes](https://developer.wordpress.org/plugins/shortcodes)
- [ ] [Shortcodes > Basic Shortcodes](https://developer.wordpress.org/plugins/shortcodes/basic-shortcodes)
- [ ] [Shortcodes > Enclosing Shortcodes](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes)
- [ ] [Shortcodes > Shortcodes with Parameters](https://developer.wordpress.org/plugins/shortcodes/shortcodes-with-parameters)
- [ ] [Shortcodes > TinyMCE Enhanced Shortcodes](https://developer.wordpress.org/plugins/shortcodes/tinymce-enhanced-shortcodes)
- [x] [Settings](https://developer.wordpress.org/plugins/settings) #28 
- [ ] [Settings > Settings API](https://developer.wordpress.org/plugins/settings/settings-api)
- [ ] [Settings > Using Settings API](https://developer.wordpress.org/plugins/settings/using-settings-api)
- [ ] [Settings > Options API](https://developer.wordpress.org/plugins/settings/options-api)
- [ ] [Settings > Custom Settings Page](https://developer.wordpress.org/plugins/settings/custom-settings-page)
- [x] [Metadata](https://developer.wordpress.org/plugins/metadata) #34
- [ ] [Metadata > Managing Post Metadata](https://developer.wordpress.org/plugins/metadata/managing-post-metadata)
- [ ] [Metadata > Custom Meta Boxes](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes)
- [ ] [Metadata > Rendering Post Metadata](https://developer.wordpress.org/plugins/metadata/rendering-post-metadata)
- [x] [Custom Post Types](https://developer.wordpress.org/plugins/post-types) #26
- [ ] [Custom Post Types > Registering Custom Post Types](https://developer.wordpress.org/plugins/post-types/registering-custom-post-types)
- [ ] [Custom Post Types > Working with Custom Post Types](https://developer.wordpress.org/plugins/post-types/working-with-custom-post-types)
- [x] [Taxonomies](https://developer.wordpress.org/plugins/taxonomies) #36
- [ ] [Taxonomies > Working with Custom Taxonomies](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies)
- [ ] [Taxonomies > Term Splitting (WordPress 4.2)](https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2)
- [ ] [Users](https://developer.wordpress.org/plugins/users)
- [ ] [Users > Working with Users](https://developer.wordpress.org/plugins/users/working-with-users)
- [ ] [Users > Working with User Metadata](https://developer.wordpress.org/plugins/users/working-with-user-metadata)
- [ ] [Users > Roles and Capabilities](https://developer.wordpress.org/plugins/users/roles-and-capabilities)
- [ ] [HTTP API](https://developer.wordpress.org/plugins/http-api)
- [x] [JavaScript, Ajax, & jQuery](https://developer.wordpress.org/plugins/javascript) #32
- [ ] [JavaScript, Ajax, & jQuery > jQuery](https://developer.wordpress.org/plugins/javascript/jquery)
- [ ] [JavaScript, Ajax, & jQuery > AJAX](https://developer.wordpress.org/plugins/javascript/ajax)
- [ ] [JavaScript, Ajax, & jQuery > Server Side PHP and Enqueuing](https://developer.wordpress.org/plugins/javascript/enqueuing)
- [ ] [JavaScript, Ajax, & jQuery > Heartbeat API](https://developer.wordpress.org/plugins/javascript/heartbeat-api)
- [ ] [JavaScript, Ajax, & jQuery > Summary](https://developer.wordpress.org/plugins/javascript/summary)
- [ ] [Cron](https://developer.wordpress.org/plugins/cron)
- [ ] [Cron > Understanding WP-Cron Scheduling](https://developer.wordpress.org/plugins/cron/understanding-wp-cron-scheduling)
- [ ] [Cron > Scheduling WP Cron Events](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events)
- [ ] [Cron > Hooking WP-Cron Into the System Task Scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler)
- [ ] [Cron > Testing of WP-Cron](https://developer.wordpress.org/plugins/cron/simple-testing)
- [ ] [Internationalization](https://developer.wordpress.org/plugins/internationalization)
- [ ] [Internationalization](https://developer.wordpress.org/plugins/internationalization/localization)
- [ ] [Internationalization > Localization](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin)
- [ ] [Internationalization > How to Internationalize Your Plugin](https://developer.wordpress.org/plugins/internationalization/security)
- [ ] [The Plugin Directory > Internationalization Security](https://developer.wordpress.org/plugins/wordpress-org)
- [ ] [The Plugin Directory > Detailed Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines)
- [ ] [The Plugin Directory > Planning Plugins](https://developer.wordpress.org/plugins/wordpress-org/planning-submitting-and-maintaining-plugins)
- [ ] [The Plugin Directory > Using Subversion](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion)
- [ ] [The Plugin Directory > Alerts and Warnings](https://developer.wordpress.org/plugins/wordpress-org/alerts-and-warnings)
- [ ] [The Plugin Directory > Managing Your Plugin’s Security](https://developer.wordpress.org/plugins/wordpress-org/plugin-security)
- [ ] [The Plugin Directory > Developer FAQ](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq)
- [x] [Developer Tools](https://developer.wordpress.org/plugins/developer-tools) #18
- [ ] [Developer Tools > Debug Bar and Add-Ons](https://developer.wordpress.org/plugins/developer-tools/debug-bar-and-add-ons)
- [ ] [Developer Tools > Helper Plugins](https://developer.wordpress.org/plugins/developer-tools/helper-plugins)
- [x] [Credits](https://developer.wordpress.org/plugins/credits) #2

**Comment by t-hamano** [comment]
Pluugin HandbookのGitHub化が提案されているようです。
作業再開は、そのGitHub化が落ち着いてからの方がよいかもしれません。
https://meta.trac.wordpress.org/ticket/7358

**Comment by t-hamano** [comment]
Update:

プラグインハンドブックの原文がGitHubで管理されるようになったことで、日本語版もそのリポジトリをフォークして翻訳を進めることになりました（[jawordpressorg / developer-plugins-handbook](https://github.com/jawordpressorg/developer-plugins-handbook)）。

そのため、当issueはクローズします。

新リポジトリでのTracking Issueはこちら：https://github.com/jawordpressorg/developer-plugins-handbook/issues/1
